// Code generated by Slice Machine. DO NOT EDIT.

import dynamic from "next/dynamic";

export const components = {
  hero_background_image: dynamic(() => import("./HeroBackgroundImage")),
  navigation_item: dynamic(() => import("./NavigationItem")),
};
